### ISSUE TITLE
Which commit of OpenDF should be used?

### ISSUE THREAD

**Issue by hao-fang** [amazon-science/dataflow-evaluation-toolkit#3]
Dear authors,

Thank you very much for developing the toolkit!

I tried to follow the guideline and failed at this step when applying the patches.
```bash
git clone https://github.com/telepathylabsai/OpenDF.git
cd OpenDF
git apply ../opendf_changes.patch
mv opendf ../src/.
cd ..
```

I think OpenDF has some new commits which conflicts with the patch. Can you share which commit of OpenDF we should use to apply the patch? Thanks!

**Comment by dbonadiman** [comment]
Hello,
The specific commit we used for OpenDF is [0110db2af5a295a1daa0d08527841fa593446b8c](https://github.com/telepathylabsai/OpenDF/tree/0110db2af5a295a1daa0d08527841fa593446b8c).

**Comment by hankcs** [comment]
@hao-fang I wrote a script to automate the installation: https://github.com/hankcs/dataflow-evaluation-toolkit

BTW, I'm presenting the demo Saturday 6:15-8:15pm, February 11, 2023 at [AAAI 23](https://aaai-23.aaai.org/demonstration-program/). I've set up a live demo at https://dfee.hankcs.com/ and it will be online till Feb 14. Feel free to play with it and have fun :)

**Comment by hao-fang** [comment]
Thanks @dbonadiman and @hankcs! Very nice demo!
